### ISSUE TITLE
Update website theme to better match CNY Hackathon branding / website color scheme

### ISSUE THREAD

**Issue by tbutts** [pereztr5/cyboard#16]
Since last year, there have been a handful of changes to the main website for CNY Hackathon, including the new logo (the one with the fire, and the USB symbol that evokes the feeling of a murder weapon from Clue). In an effort to not clash against the design of the hackathon homepage, our CSS should be updated in an attempt to mirror the homepage.

The main website's design is now very minimal, opts for only 2 tones of blue for links / buttons, and pure black text on white background. From some scrounging, it seems to be the "Frank" WordPress theme, which is a no-frills wp theme. [More detail here](https://www.smashingmagazine.com/2013/01/frank-a-wordpress-theme-designed-for-speed/).

Sample of the current page:
![cnyhack-main-web](https://cloud.githubusercontent.com/assets/10280999/24940356/9bbe7fae-1f10-11e7-894c-503aa9eacd0f.PNG)

The logo, as you can see, has that red-orange, along with many more tones of white to gray to black. I'd like to try out a theme that has those colors, if only because it gives us more to work with.

Strictly speaking, the Scoring website should simply move away from the current dark theme, to a light theme. That would be enough to reduce the shock when contestants likely begin the competition by clicking a link on the CNY Hackathon homepage that leads to the Scoring website.

**Comment by pereztr5** [comment]
Agree, although I will miss the dark theme as that is my default for everything 😫

**Comment by tbutts** [comment]
It will be missed! But don't worry, there will be other projects to give the good ol' matrix look to.
